name : CI-Ci deployment
 
on :
  push:
   branches: ["main"]

jobs :
 build-deploy:
  runs-on : ubuntu-latest

  steps:

   - name : Check out
     uses : actions/checkout@v3

   - name : setup node
     uses : actions/setup-node@v3
     with:
      node-version: 20.19
  
   - name: Install dependencies
     run: npm install


   - name: Build frontend
     run: npm run build

      # 5. Run tests
   - name: Run tests
     run: npm test
# 6. Deploy to Render
   - name: Deploy Frontend
     run: curl -X POST ${{ secrets.RENDER_FRONTEND_HOOK }}

